"""new fields in user model

Revision ID: 97989581b3d4
Revises: fbeafb7223f3
Create Date: 2019-06-18 01:08:58.893161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97989581b3d4'
down_revision = 'fbeafb7223f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
